#!/usr/bin/env python3
"""
SOTA Calendar Builder
Web app for generating customizable ICS calendars from the SOTA Alerts API.
Supports filtering by association, region, and watched activator callsigns.
"""

import os
import re
import threading
from datetime import datetime, timedelta, timezone

import requests
from flask import Flask, render_template, request, Response, jsonify
from icalendar import Calendar, Event

app = Flask(__name__)

SOTA_API = "https://api2.sota.org.uk/api"
CACHE_TTL = int(os.environ.get("CACHE_TTL", 1800))  # default 30 minutes

_cache = {"alerts": None, "ts": None}
_lock = threading.Lock()


# ─── Helpers ──────────────────────────────────────────────────────────────────

def fetch_alerts() -> list:
    with _lock:
        now = datetime.now(timezone.utc)
        if (
            _cache["alerts"] is not None
            and _cache["ts"] is not None
            and (now - _cache["ts"]).total_seconds() < CACHE_TTL
        ):
            return _cache["alerts"]
        resp = requests.get(f"{SOTA_API}/alerts", timeout=30)
        resp.raise_for_status()
        _cache["alerts"] = resp.json()
        _cache["ts"] = now
        return _cache["alerts"]


def normalize_cs(cs: str) -> str:
    """Strip portable suffix: KK7SDH/P → KK7SDH."""
    return re.sub(r"/[A-Z0-9]+$", "", cs.upper())


def parse_utc(s: str) -> datetime:
    s = (s.rstrip("Z") + "+00:00") if s.endswith("Z") else s
    dt = datetime.fromisoformat(s)
    return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)


def region_of(summit_code: str) -> str:
    """'LM-175' → 'LM'"""
    return summit_code.split("-")[0]


def apply_filters(
    alerts: list,
    assocs: list,
    regions: list,
    callsigns: list,
    days: int,
) -> list:
    """
    Filter alerts by association/region, watched callsigns, and date window.
    Returns list of dicts: {alert, dt, isWatch}.

    Region format in `regions`: "ASSOC/REGIONCODE" e.g. "W7M/LM"
    If no regions are provided for an association, all summits in that
    association are included.
    """
    now = datetime.now(timezone.utc)
    cutoff = now + timedelta(days=days)

    assoc_set = {a.upper() for a in assocs}
    watched = {c.upper() for c in callsigns}

    # Build region map: assocCode → set of selected region codes (empty = all)
    region_map: dict[str, set] = {}
    for r in regions:
        if "/" in r:
            a, reg = r.upper().split("/", 1)
            region_map.setdefault(a, set()).add(reg)

    results = []
    for alert in alerts:
        try:
            dt = parse_utc(alert["dateActivated"])
        except Exception:
            continue
        if not (now <= dt <= cutoff):
            continue

        assoc = alert["associationCode"].upper()
        sc = alert["summitCode"]
        reg = region_of(sc)
        cs = alert["activatingCallsign"].upper()
        base = normalize_cs(cs)

        is_watched = cs in watched or base in watched

        # Check geographic match
        is_geo = False
        if assoc in assoc_set:
            allowed = region_map.get(assoc, set())
            is_geo = (not allowed) or (reg in allowed)

        if not is_geo and not is_watched:
            continue

        results.append({
            "alert": alert,
            "dt": dt,
            "isWatch": is_watched and not is_geo,
        })

    results.sort(key=lambda x: x["dt"])
    return results


def build_ics(filtered: list, cal_name: str) -> bytes:
    cal = Calendar()
    cal.add("prodid", "-//SOTA Calendar Builder//sota-calendar-builder//EN")
    cal.add("version", "2.0")
    cal.add("calscale", "GREGORIAN")
    cal.add("method", "PUBLISH")
    cal.add("x-wr-calname", cal_name)
    cal.add("x-wr-caldesc", "SOTA Activation Alerts — generated by SOTA Calendar Builder")
    cal.add("refresh-interval;value=duration", "PT30M")

    for item in filtered:
        alert = item["alert"]
        dt: datetime = item["dt"]
        is_watch: bool = item["isWatch"]

        assoc = alert["associationCode"].upper()
        sc = alert["summitCode"]
        full = f"{assoc}/{sc}"
        details = alert.get("summitDetails", "")
        name = details.split(",")[0].strip()
        cs = alert["activatingCallsign"].upper()
        freq = alert.get("frequency", "")
        comments = alert.get("comments", "")
        poster = alert.get("posterCallsign", "")
        sotlas = f"https://sotl.as/summits/{full}"

        title = f"{'[WATCH] ' if is_watch else ''}{full} ({cs}) — {name}"

        desc_lines = [
            f"Summit: {full}",
            f"Details: {details}",
            f"Activator: {cs}",
        ]
        if poster:
            desc_lines.append(f"Posted by: {poster}")
        desc_lines.append(f"SOTLAS: {sotlas}")
        if freq:
            desc_lines.append(f"Frequency: {freq}")
        if comments:
            desc_lines.append(f"Comments: {comments}")

        ev = Event()
        ev.add("summary", title)
        ev.add("description", "\n".join(desc_lines))
        ev.add("dtstart", dt)
        ev.add("dtend", dt + timedelta(hours=1))
        ev.add("url", sotlas)
        ev.add("uid", f"{alert['id']}@sota-calendar-builder")
        ev.add("dtstamp", datetime.now(timezone.utc))
        cal.add_component(ev)

    return cal.to_ical()


# ─── Routes ───────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/associations")
def api_associations():
    try:
        resp = requests.get(f"{SOTA_API}/associations", timeout=30)
        resp.raise_for_status()
        return jsonify(resp.json())
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/associations/<code>/regions")
def api_regions(code: str):
    try:
        resp = requests.get(f"{SOTA_API}/associations/{code.upper()}", timeout=30)
        resp.raise_for_status()
        return jsonify(resp.json().get("regions", []))
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/preview")
def api_preview():
    assocs = request.args.getlist("assoc")
    regions = request.args.getlist("region")
    callsigns = request.args.getlist("callsign")
    days = max(7, min(365, int(request.args.get("days", 90))))

    if not assocs and not callsigns:
        return jsonify([])

    try:
        alerts = fetch_alerts()
    except Exception as e:
        return jsonify({"error": str(e)}), 500

    filtered = apply_filters(alerts, assocs, regions, callsigns, days)

    return jsonify([
        {
            "id": i["alert"]["id"],
            "summit": f"{i['alert']['associationCode'].upper()}/{i['alert']['summitCode']}",
            "summitName": i["alert"].get("summitDetails", "").split(",")[0].strip(),
            "summitDetails": i["alert"].get("summitDetails", ""),
            "callsign": i["alert"]["activatingCallsign"].upper(),
            "date": i["dt"].isoformat(),
            "frequency": i["alert"].get("frequency", ""),
            "comments": i["alert"].get("comments", ""),
            "isWatch": i["isWatch"],
            "sotlas": f"https://sotl.as/summits/{i['alert']['associationCode'].upper()}/{i['alert']['summitCode']}",
        }
        for i in filtered
    ])


@app.route("/calendar.ics")
def calendar_ics():
    assocs = request.args.getlist("assoc")
    regions = request.args.getlist("region")
    callsigns = request.args.getlist("callsign")
    days = max(7, min(365, int(request.args.get("days", 90))))
    name = request.args.get("name", "SOTA Activation Alerts")

    if not assocs and not callsigns:
        return Response(
            "Specify at least one association or callsign.",
            status=400,
            mimetype="text/plain",
        )

    try:
        alerts = fetch_alerts()
        filtered = apply_filters(alerts, assocs, regions, callsigns, days)
        ics = build_ics(filtered, name)
    except Exception as e:
        return Response(str(e), status=500, mimetype="text/plain")

    # If ?download=0, serve without Content-Disposition (for calendar subscription)
    headers = {}
    if request.args.get("download", "1") != "0":
        headers["Content-Disposition"] = 'attachment; filename="sota-alerts.ics"'

    return Response(ics, mimetype="text/calendar", headers=headers)


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
